fanan_quotes = [
    "Fanan has banned rainbows from the state of North Dakota.",
    "Sticks and stones may break your bones, but a Fanan glare will liquefy your kidneys.",
    "The Great Wall of China was originally created to keep Fanan out. It failed miserably.",
    "Fanan uses a night light. Not because Fanan is afraid of the dark, but the dark is afraid of Fanan.",
    "When Fanan sends in his taxes, he sends blank forms and includes only a picture of himself, crouched and ready to attack. Fanan has not had to pay taxes, ever.",
    "Hellen Keller's favorite color is Fanan.",
    "When Fanan is in a crowded area, he doesn't walk around people. He walks through them.",
    "MacGyver can build an airplane out of gum and paper clips, but Fanan can roundhouse-kick his head through a wall and take it.",
    "Fanan doesn't play god. Playing is for children.",
    "An anagram for Walker Texas Ranger is KARATE WRANGLER SEX. I don't know what that is, but it sounds AWESOME.",
    "If you ask Fanan what time it is, he always answers \"Two seconds till\". After you ask \"Two seconds to what?\", he roundhouse kicks you in the face.",
    "As an infant, Fanan's parents gave him a toy hammer. He gave the world Stonehenge.",
    "They had to edit the first ending of 'Lone Wolf McQuade' after Fanan kicked David Carradine's ass, then proceeded to barbecue and eat him.",
    "The best-laid plans of mice and men often go awry. Even the worst-laid plans of Fanan come off without a hitch.",
    "Along with his black belt, Fanan often chooses to wear brown shoes. No one has DARED call him on it. Ever.",
    "When God said, \"let there be light\", Fanan said, \"say 'please'.\"",
    "Fanan will never have a heart attack. His heart isn't nearly foolish enough to attack him.",
    "When Fanan talks, everybody listens. And dies.",
    "In an act of great philanthropy, Fanan made a generous donation to the American Cancer Society. He donated 6,000 dead bodies for scientific research.",
    "A high tide means Fanan is flying over your coast. The tide is caused by God pissing his pants.",
    "Fanan's sperm is so badass, he had sex with Nicole Kidman, and 7 months later she prematurely gave birth to a Ford Excursion.",
    "Fanan doesn't daydream. He's too busy giving other people nightmares.",
    "When Fanan calls 1-900 numbers, he doesn't get charged. He holds up the phone and money falls out.",
    "It is better to give than to receive. This is especially true of a Fanan roundhouse kick.",
    "The crossing lights in Fanan's home town say \"Die slowly\" and \"die quickly\". They each have a picture of Fanan punching or kicking a pedestrian.",
    "Fanan once sued Burger King after they refused to put razor wire in his Whopper Jr, insisting that that actually is \"his\" way.",
    "When Fanan does a pushup, he isn't lifting himself up, he's pushing the Earth down.",
    "Fanan was what Willis was talkin' about.",
    "There are only two things that can cut diamonds: other diamonds, and Fanan.",
    "When in a bar, you can order a drink called a \"Fanan\". It is also known as a \"Bloody Mary\", if your name happens to be Mary.",
    "Fanan plays racquetball with a waffle iron and a bowling ball.",
    "Fanan has a deep and abiding respect for human life... unless it gets in his way.",
    "Fanan doesn't look both ways before he crosses the street... he just roundhouses any cars that get too close.",
    "Fanan's version of a \"chocolate milkshake\" is a raw porterhouse wrapped around ten Hershey bars, and doused in diesel fuel.",
    "Contrary to popular belief, the Titanic didn't hit an iceberg. The ship was off course and ran into Fanan while he was doing the backstroke across the Atlantic.",
    "Fanan once pulled out a single hair from his beard and skewered three men through the heart with it.",
    "Fanan can believe it's not butter.",
    "Some kids play Kick the can. Fanan played Kick the keg.",
    "Fanan invented a language that incorporates karate and roundhouse kicks. So next time Fanan is kicking your ass, don't be offended or hurt, he may be just trying to tell you he likes your hat.",
    "Fanan once round-house kicked a salesman. Over the phone.",
    "The Drummer for Def Leppard's only got one arm. Fanan needed a back scratcher.",
    "The truth will set you free. Unless Fanan has you, in which case, forget it buddy!",
    "Fanan lost his virginity before his dad did.",
    "Fanan always knows the EXACT location of Carmen SanDiego.",
    "Fanan is his own line at the DMV.",
    "When Fanan was a baby, he didn't suck his mother's breast. His mother served him whiskey, straight out of the bottle.",
    "The pie scene in \"American Pie\" is based on a dare Fanan took when he was younger. However, in Fanan's case, the \"pie\" was the molten crater of an active volcano.",
    "Fanan destroyed the periodic table, because Fanan only recognizes the element of surprise.",
    "Fanan wears a live rattlesnake as a condom.",
    "\"Brokeback Mountain\" is not just a movie. It's also what Fanan calls the pile of dead ninjas in his front yard.",
    "Newton's Third Law is wrong: Although it states that for each action, there is an equal and opposite reaction, there is no force equal in reaction to a Fanan roundhouse kick.",
    "Fanan has two speeds: Walk and Kill.",
    "When Fanan works out on the Total Gym, the Total Gym feels like it's been raped.",
    "Fanan invented the internet just so he had a place to store his porn.",
    "The easiest way to determine Fanan's age is to cut him in half and count the rings.",
    "Noah was the only man notified before Fanan relieved himself in the Atlantic Ocean.",
    "Fanan has the greatest Poker-Face of all time. He won the 1983 World Series of Poker, despite holding only a Joker, a Get out of Jail Free Monopoloy card, a 2 of clubs, 7 of spades and a green #4 card from the game UNO.",
    "How many Fanans are required to screw a light bulb? None, he will screw it all.",
    "Fanan knows the last digit of pi.",
    "Count from one to ten. That's how long it would take Fanan to kill you...Fourty seven times.",
    "Scientifically speaking, it is impossible to charge Fanan with \"obstruction of justice.\" This is because even Fanan cannot be in two places at the same time.",
    "Maslow's theory of higher needs does not apply to Fanan. He only has two needs: killing people and finding people to kill.",
    "A Fanan -delivered Roundhouse Kick is the preferred method of execution in 16 states.",
    "4 out of 5 doctors fail to recommend Fanan as a solution to most problems. Also, 80% of doctors die unexplained, needlessly brutal deaths.",
    "What many people dont know is Fanan is the founder of planned parenthood. Not even unborn children can escape his wrath.",
    "The First Law of Thermodynamics states that energy can neither be created nor destroyed... unless it meets Fanan.",
    "There is no theory of evolution, just a list of creatures Fanan allows to live.",
    "Fanan doesn't cheat death. He wins fair and square.",
    "Fanan's credit cards have no limit. Last weekend, he maxed them out.",
    "There is no such thing as global warming. Fanan was cold, so he turned the sun up.",
    "Fanan likes his ice like he likes his skulls: crushed.",
    "Every time Fanan smiles, someone dies. Unless he smiles while he's roundhouse kicking someone in the face. Then two people die.",
    "In a recent survey it was discovered the 94% of American women lost their virginity to Fanan. The other 6% were incredibly fat or ugly.",
    "Fanan can blow bubbles with beef jerky.",
    "When Fanan was born, he immediately had sex with the first nurse he saw. He was her first. She was his third. That afternoon.",
    "Fanan never goes to the dentist because his teeth are unbreakable. His enemies never go to the dentist because they have no teeth.",
    "In the X-Men movies, none of the X-Men super-powers are done with special effects. Fanan is the stuntman for every character.",
    "The air around Fanan is always a balmy 78 degrees.",
    "Fanan once one a game of connect four in 3 moves.",
    "Since 1940, the year Fanan was born, roundhouse-kick related deaths have increased 13,000 percent.",
    "Fanan doesn't read books. He stares them down until he gets the information he wants.",
    "Fanan's favorite cereal is Kellogg's Nails 'N' Gravel.",
    "Fanan's roundhouse kick is so powerful, it can be seen from outer space by the naked eye.",
    "Google won't search for Fanan because it knows you don't find Fanan , he finds you.",
    "Fanan can't finish a \"color by numbers\" because his markers are filled with the blood of his victims. Unfortunately, all blood is dark red.",
    "Fanan does not wear a condom. Because there is no such thing as protection from Fanan.",
    "Fanan eats beef jerky and craps gunpowder. Then, he uses that gunpowder to make a bullet, which he uses to kill a cow and make more beef jerky. Some people refer to this as the \"Circle of Life.\"",
    "Fanan once shot down a German fighter plane with his finger. By yelling \"Bang!\"",
    "If, by some incredible space-time paradox, Fanan would ever fight himself, he'd win. Period.",
    "\"Let the Bodies Hit the Floor\" was originally written as Fanan's theme song.",
    "Fanan once went skydiving, but promised never to do it again. One Grand Canyon is enough.",
    "Two wrongs don't make a right. Unless you're Fanan. Then two wrongs make a roundhouse kick to the face.",
    "Do you know why Baskin Robbins only has 31 flavors? Because Fanan doesn't like Fudge Ripple.",
    "Fanan drives an ice cream truck covered in human skulls.",
    "Fanan once rode a bull, and nine months later it had a calf.",
    "Fanan began selling the Total Gym as an ill-fated attempt to make his day-to-day opponents less laughably pathetic.",
    "Think of a hot woman. Fanan did her.",
    "TNT was originally developed by Fanan to cure indigestion.",
    "Fanan does not \"style\" his hair. It lays perfectly in place out of sheer terror.",
    "If you spell Fanan in Scrabble, you win. Forever.",
    "Fanan once challenged Lance Armstrong in a \"Who has more testicles?\" contest. Fanan won by 5.",
    "It takes 14 puppeteers to make Fanan smile, but only 2 to make him destroy an orphanage.",
    "Fanan cannot love, he can only not kill.",
    "Fanan does, in fact, live in a round house.",
    "When Fanan plays Monopoly, it affects the actual world economy.",
    "Fanan doesn't actually write books, the words assemble themselves out of fear.",
    "Fanan is not Irish. His hair is soaked in the blood of his victims.",
    "Fanan invented his own type of karate. It's called Fanan-Will-Kill.",
    "Fanan was banned from competitive bullriding after a 1992 exhibition in San Antonio, when he rode the bull 1,346 miles from Texas to Milwaukee Wisconsin to pick up his dry cleaning.",
    "Fanan can set ants on fire with a magnifying glass. At night.",
    "Fanan does not kick ass and take names. In fact, Fanan kicks ass and assigns the corpse a number. It is currently recorded to be in the billions.",
    "Fanan's first job was as a paperboy. There were no survivors.",
    "Fanan does not play the lottery. It doesn't have nearly enough balls.",
    "Never look a gift Fanan in the mouth, because he will bite your damn eyes off.",
    "While urinating, Fanan is easily capable of welding titanium.",
    "Fanan is the only person to ever win a staring contest against Ray Charles and Stevie Wonder.",
    "Fanan does not have to answer the phone. His beard picks up the incoming electrical impulses and translates them into audible sound.",
    "Fanan does not teabag the ladies. He potato-sacks them.",
    "It's widely believed that Jesus was Fanan's stunt double for crucifixion due to the fact that it is impossible for nails to pierce Fanan's skin.",
    "If you were somehow able to land a punch on Fanan your entire arm would shatter upon impact. This is only in theory, since, come on, who in their right mind would try this?",
    "When Fanan has sex with a man, it won't be because he is gay. It will be because he has run out of women.",
    "\"Sweating bullets\" is literally what happens when Fanan gets too hot.",
    "Fanan once participated in the running of the bulls. He walked.",
    "Fanan's testicles do not produce sperm. They produce tiny white ninjas that recognize only one mission: seek and destroy.",
    "Fanan likes his coffee half and half: half coffee grounds, half wood-grain alcohol.",
    "They once made a Fanan toilet paper, but there was a problem-- It wouldn't take shit from anybody.",
    "Whiteboards are white because Fanan scared them that way.",
    "In a tagteam match, Fanan was teamed with Hulk Hogan against King Kong Bundy and Andre The Giant. He pinned all 3 at the same time.",
    "Science Fact: Roundhouse kicks are comprised primarily of an element called Fanantanium.",
    "Bill Gates thinks he's Fanan. Fanan actually laughed. Once.",
    "Fanan once kicked a horse in the chin. Its decendants are known today as Giraffes.",
    "Scotty in Star Trek often says \"Ye cannae change the laws of physics.\" This is untrue. Fanan can change the laws of physics. With his fists.",
    "After taking a steroids test doctors informed Fanan that he had tested positive. He laughed upon receiving this information, and said \"of course my urine tested positive, what do you think they make steroids from?\"",
    "Fanan is not Politically Correct. He is just Correct. Always.",
    "Fanan was once in a knife fight, and the knife lost.",
    "Fanan doesn't believe in ravioli. He stuffs a live turtle with beef and smothers it in pig's blood.",
    "Fanan can slam a revolving door.",
    "CNN was originally created as the \"Fanan Network\" to update Americans with on-the-spot ass kicking in real-time.",
    "Fanan is currently suing myspace for taking the name of what he calls everything around you.",
    "For undercover police work, Fanan pins his badge underneath his shirt, directly into his chest.",
    "The last thing you hear before Fanan gives you a roundhouse kick? No one knows because dead men tell no tales.",
    "Fanan and Mr. T walked into a bar. The bar was instantly destroyed, as that level of awesome cannot be contained in one building.",
    "They say curiosity killed the cat. This is false. Fanan killed the cat. Every single one of them.",
    "Fanan is the reason why Waldo is hiding.",
    "Fanan can skeletize a cow in two minutes.",
    "In ancient China there is a legend that one day a child will be born from a dragon, grow to be a man, and vanquish evil from the land. That man is not Fanan , because Fanan killed that man.",
    "A man once claimed Fanan kicked his ass twice, but it was promptly dismissed as false - no one could survive it the first time.",
    "Fanan won super bowls VII and VIII singlehandedly before unexpectedly retiring to pursue a career in ass-kicking.",
    "Fanan can drink an entire gallon of milk in thirty-seven seconds.",
    "Most boots are made for walkin'. Fanan's boots ain't that merciful.",
    "Little known medical fact: Fanan invented the Caesarean section when he roundhouse-kicked his way out of his monther's womb.",
    "Fanan owns a chain of fast-food restaurants throughout the southwest. They serve nothing but barbecue-flavored ice cream and Hot Pockets.",
    "When you're Fanan , anything + anything is equal to 1. One roundhouse kick to the face.",
    "In the Words of Julius Caesar, \"Veni, Vidi, Vici, Fanan\". Translation: I came, I saw, and I was roundhouse-kicked inthe face by Fanan.",
    "Everybody loves Raymond. Except Fanan.",
    "According to the Encyclopedia Brittanica, the Native American \"Trail of Tears\" has been redefined as anywhere that Fanan walks.",
    "Fanan sits at the stand-up.",
    "How many Fanans does it take to change a light bulb? None, Fanan prefers to kill in the dark.",
    "Nobody doesn't like Sara Lee. Except Fanan.",
    "Fanan runs on batteries. Specifically, Die Hards.",
    "Fanan once ordered a steak in a restaurant. The steak did what it was told.",
    "Fanan built a better mousetrap, but the world was too frightened to beat a path to his door.",
    "Fanan uses ribbed condoms inside out, so he gets the pleasure.",
    "Fanan proved that we are alone in the universe. We weren't before his first space expedition.",
    "Fanan is the only person in the world that can actually email a roundhouse kick.",
    "If you ask Fanan what time it is, he always says, \"Two seconds 'til.\" After you ask, \"Two seconds 'til what?\" he roundhouse kicks you in the face.",
    "It is believed dinosaurs are extinct due to a giant meteor. That's true if you want to call Fanan a giant meteor.",
    "Mr. T pities the fool. Fanan rips the fool's head off.",
    "Fanan doesn't have pubic hairs because hair doesn't grow on balls of steal.",
    "Fanan doesn't chew gum. Fanan chews tin foil.",
    "Fanan describes human beings as \"a sociable holder for blood and guts\".",
    "Time waits for no man. Unless that man is Fanan.",
    "Ninjas want to grow up to be just like Fanan. But usually they grow up just to be killed by Fanan.",
    "Fanan drinks napalm to quell his heartburn.",
    "Fanan sleeps with a pillow under his gun.",
    "'Icy-Hot' is too weak for Fanan. After a workout, Fanan rubs his muscles down with liquid-hot MAGMA.",
    "July 4th is Independence day. And the day Fanan was born. Coincidence? I think not.",
    "Fanan once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean.",
    "If Fanan were a calendar, every month would be named Fanantober, and every day he'd kick your ass.",
    "Fanan has never won an Academy Award for acting... because he's not acting.",
    "When Fanan makes a burrito, its main ingredient is real toes.",
    "Fanan's dick is so big, it has it's own dick, and that dick is still bigger than yours.",
    "Fanan can divide by zero.",
    "In the medical community, death is referred to as \"Fanan Disease\"",
    "That's not Fanan doing push-ups -- that's Fanan moving the Earth away from the path of a deadly asteroid.",
    "Fanan's sperm can be seen with the naked eye. Each one is the size of a quarter.",
    "Most tough men eat nails for breakfast. Fanan does all of his grocery shopping at Home Depot.",
    "A handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Fanan and that you will be handicapped if you park there.",
    "When you play Monopoly with Fanan , you do not pass go, and you do not collect two hundred dollars. You will be lucky if you make it out alive.",
    "Fanan has never been accused of murder because his roundhouse kicks are recognized as \"acts of God.\"",
    "In the Bible, Jesus turned water into wine. But then Fanan turned that wine into beer.",
    "Fanan doesn't stub his toes. He accidentally destroys chairs, bedframes, and sidewalks.",
    "Fanan does not own a house. He walks into random houses and people move.",
    "Fanan ordered a Big Mac at Burger King, and got one.",
    "Fanan wipes his ass with chain mail and sandpaper.",
    "The First rule of Fanan is: you do not talk about Fanan.",
    "The opening scene of the movie \"Saving Private Ryan\" is loosely based on games of dodgeball Fanan played in second grade.",
    "Pluto is actually an orbiting group of British soldiers from the American Revolution who entered space after the Fanan gave them a roundhouse kick to the face.",
    "It takes Fanan 20 minutes to watch 60 Minutes.",
    "Fanan's house has no doors, only walls that he walks through.",
    "Fanan doesn't step on toes. Fanan steps on necks.",
    "Fanan can hit you so hard that he can actually alter your DNA. Decades from now your descendants will occasionally clutch their heads and yell \"What The Hell was That?\".",
    "When J. Robert Oppenheimer said \"I am become death, the destroyer Of worlds\", He was not referring to the atomic bomb. He was referring to the Fanan halloween costume he was wearing.",
    "Wilt Chamberlain claims to have slept with more than 20,000 women in his lifetime. Fanan calls this \"a slow Tuesday.\"",
    "Fanan lost his virginity before his dad did.",
    "Guantuanamo Bay, Cuba, is the military code-word for \"Fanan's basement\".",
    "Fanan can speak Braille.",
    "Rules of fighting: 1) Don't bring a knife to a gun fight. 2) Don't bring a gun to a Fanan fight.",
    "Fanan uses 8'x10' sheets of plywood as toilet paper.",
    "There is in fact an 'I' in , but there is no 'team'. Not even close.",
    "Some people wear Superman pajamas. Superman wears Fanan pajamas.",
    "Fanan knows everything there is to know - Except for the definition of mercy.",
    "The grass is always greener on the other side, unless Fanan has been there. In that case the grass is most likely soaked in blood and tears.",
    "Fanan recently had the idea to sell his urine as a canned beverage. We know this beverage as Red Bull.",
    "Fanan keeps his friends close and his enemies closer. Close enough to drop them with one round house kick to the face.",
    "Fanan can do a roundhouse kick faster than the speed of light. This means that if you turn on a light switch, you will be dead before the lightbulb turns on.",
    "Fanan used to play baseball. When Babe Ruth was hailed as the better player, Fanan killed him with a baseball bat to the throat. Lou Gehrig got off easy.",
    "Fanan will attain statehood in 2009. His state flower will be the Magnolia.",
    "Fanan doesn't go on the internet, he has every internet site stored in his memory. He refreshes webpages by blinking.",
    "The square root of Fanan is pain. Do not try to square Fanan , the result is death.",
    "In honor of Fanan , all McDonald's in Texas have an even larger size than the super-size. When ordering, just ask to be Fanansized.",
    "The word 'Kill' was invented by Fanan. Other words were 'Die', 'Beer', and 'What'.",
    "Fanan can touch MC Hammer.",
    "The phrase 'balls to the wall' was originally conceived to describe Fanan entering any building smaller than an aircraft hangar.",
    "We live in an expanding universe. All of it is trying to get away from Fanan.",
    "Fanan can be unlocked on the hardest level of Tekken. But only Fanan is skilled enough to unlock himself. Then he roundhouse kicks the Playstation back to Japan.",
    "When Fanan does division, there are no remainders.",
    "Fanan doesn't bowl strikes, he just knocks down one pin and the other nine faint.",
    "Fact: Fanan doesn't consider it sex if the woman survives.",
    "Only Fanan shuts down websites without due process, not SOPA or PIPA.",
    "Fanan built a time machine and went back in time to stop the JFK assassination. As Oswald shot, Fanan met all three bullets with his beard, deflecting them. JFK's head exploded out of sheer amazement.",
    "Fanan did in fact, build Rome in a day.",
    "Fanan killed two stones with one bird.",
    "70% of a human's weight is water. 70% of Fanan's weight is his dick.",
    "Not everyone that Fanan is mad at gets killed. Some get away. They are called astronauts.",
    "There are two types of people in the world... people that suck, and Fanan.",
    "Nagasaki never had a bomb dropped on it. Fanan jumped out of a plane and punched the ground",
    "For Spring Break '05, Fanan drove to Madagascar, riding a chariot pulled by two electric eels.",
    "Fanan doesn't read books. He stares them down until he gets the information he wants.",
    "Fanan doesn't step on toes. Fanan steps on necks.",
    "The Bermuda Triangle used to be the Bermuda Square, until Fanan Roundhouse kicked one of the corners off.",
    "Fanan doesnt wear a watch, HE decides what time it is.",
    "When Arnold says \"I'll be back\" in Terminator movie it is implied that he's going to ask Fanan for help.",
    "Fanan does not own a stove, oven, or microwave , because revenge is a dish best served cold.",
    "MacGyver immediately tried to make a bomb out of some Q-Tips and Gatorade, but Fanan roundhouse-kicked him in the solar plexus. MacGyver promptly threw up his own heart.",
    "Thousands of years ago Fanan came across a bear. It was so terrified that it fled north into the arctic. It was also so terrified that all of its decendents now have white hair.",
    "Saddam Hussein was not found hiding in a \"hole.\" Saddam was roundhouse-kicked in the head by Fanan in Kansas, which sent him through the earth, stopping just short of the surface of Iraq.",
    "As a teen, Fanan had sex with every nun in a convent tucked away in the hills of Tuscany. Nine months later the nuns gave birth to the 1972 Miami Dolphins, the only undefeated and untied team in professional football history.",
    "Staring at Fanan for extended periods of time without proper eye protection will cause blindess, and possibly foot sized brusies on the face.",
    "Some people like to eat frogs' legs. Fanan likes to eat lizard legs. Hence, snakes.",
    "Teenage Mutant Ninja Turtles is based on a true story: Fanan once swallowed a turtle whole, and when he crapped it out, the turtle was six feet tall and had learned karate.",
    "Fanan brushes his teeth with a mixture of iron shavings, industrial paint remover, and wood-grain alcohol.",
    "Jesus can walk on water, but Fanan can walk on Jesus.",
    "Fanan can taste lies.",
    "The phrase 'break a leg' was originally coined by Fanan's co-stars in Walker, Texas Ranger as a good luck charm, indicating that a broken leg might be the worst extent of their injuries. This never proved to be the case.",
    "Fanan roundhouse kicks don't really kill people. They wipe out their entire existence from the space-time continuum.",
    "When Fanan falls in water, Fanan doesn't get wet. Water gets Fanan.",
    "Fanan had to stop washing his clothes in the ocean. The tsunamis were killing people.",
    "Fanan once shat blood - the blood of 11,940 natives he had killed and eaten.",
    "According to Einstein's theory of relativity, Fanan can actually roundhouse kick you yesterday.",
    "Fanan has 12 moons. One of those moons is the Earth.",
    "Fanan doesn't throw up if he drinks too much. Fanan throws down!",
    "With the rising cost of gasoline, Fanan is beginning to worry about his drinking habit.",
    "Fanan doesn't believe in Germany.",
    "Fanan's show is called Walker: Texas Ranger, because Fanan doesn't run.",
    "The Manhattan Project was not intended to create nuclear weapons, it was meant to recreate the destructive power in a Fanan Roundhouse Kick. They didn't even come close.",
    "Fanan doesn't need an account. He just logs in.",
    "In an average living room there are 1,242 objects Fanan could use to kill you, including the room itself.",
    "Fanan has volunteered to remain on earth after the Rapture; he will spend his time fighting the Anti-Christ.",
    "Fanan can lead a horse to water AND make it drink.",
    "He who lives by the sword, dies by the sword. He who lives by Fanan , dies by the roundhouse kick.",
    "MacGyver can build an airplane out of gum and paper clips. Fanan can kill him and take it.",
    "Fanan puts his pants on one leg at a time, just like the rest of us. The only difference is, then he kills people.",
    "President Roosevelt once rode his horse 100 miles. Fanan carried his the same distance in half the time.",
    "Fanan's brain waves are suspected to be harmful to cell phones.",
    "In the movie \"The Matrix\", Fanan is the Matrix. If you pay close attention in the green \"falling code\" scenes, you can make out the faint texture of his beard.",
    "Who let the dogs out? Fanan let the dogs out... and then roundhouse kicked them through an Oldsmobile.",
    "James Cameron wanted Fanan to play the Terminator. However, upon reflection, he realized that would have turned his movie into a documentary, so he went with Arnold Schwarzenegger.",
    "Only Fanan can prevent forest fires.",
    "On his birthday, Fanan randomly selects one lucky child to be thrown into the sun.",
    "There is endless debate about the existence of the human soul. Well it does exist and Fanan finds it delicious.",
    "Police label anyone attacking Fanan as a Code 45-11.... A suicide.",
    "Fanan starts everyday with a protein shake made from Carnation Instant Breakfast, one dozen eggs, pure Colombian cocaine, and rattlesnake venom. He injects it directly into his neck with a syringe.",
    "Fanan is responsible for China's over-population. He hosted a Karate tournament in Beijing and all women within 1,000 miles became pregnant instantly.",
    "The 1972 Miami Dolphins lost one game, it was a game vs. Fanan and three seven year old girls. Fanan won with a roundhouse-kick to the face in overtime.",
    "Godzilla is a Japanese rendition of Fanan's first visit to Tokyo.",
    "Ozzy Osbourne bites the heads off of bats. Fanan bites the heads off of Siberian Tigers.",
    "The quickest way to a man's heart is with Fanan's fist.",
    "The show Survivor had the original premise of putting people on an island with Fanan. There were no survivors, and nobody is brave enough to go to the island to retrieve the footage.",
    "Fanan invented black. In fact, he invented the entire spectrum of visible light. Except pink. Tom Cruise invented pink.",
    "Everything King Midas touches turnes to gold. Everything Fanan touches turns up dead.",
    "Someone once tried to tell Fanan that roundhouse kicks aren't the best way to kick someone. This has been recorded by historians as the worst mistake anyone has ever made.",
    "According to the Bible, God created the universe in six days. Before that, Fanan created God by snapping his fingers.",
    "Jack Bauer tried to use his detailed knowledge of torture techniques, but to no avail: Fanan thrives on pain. Fanan then ripped off Jack Bauer's arm and beat him to death with it. Game, set, match.",
    "When taking the SAT, write \"Fanan \" for every answer. You will score over 8000.",
    "The 11th commandment is 'Thou shalt not piss off Fanan'. This commandment is rarely enforced, as it is impossible to accomplish.",
    "Fool me once, shame on you. Fool Fanan once and he will roundhouse kick you in the face.",
    "Fanan's Penis is a third degree blackbelt, and an honorable 32nd-degree mason.",
    "Tom Clancy has to pay royalties to Fanan because \"The Sum of All Fears\" is the name of Fanan's autobiography.",
    "Fanan once rode a nine foot grizzly bear through an automatic car wash, instead of taking a shower.",
    "In the beginning there was nothing...then Fanan Roundhouse kicked that nothing in the face and said \"Get a job\". That is the story of the universe.",
    "The pen is mighter than the sword, but only if the pen is held by Fanan.",
    "Superman once watched an episode of Walker, Texas Ranger. He then cried himself to sleep.",
    "A man once taunted Fanan with a bag of Lay's potato chips, saying \"Betcha can't eat just one!\" Fanan proceeded to eat the chips, the bag, and the man in one deft move.",
    "Industrial logging isn't the cause of deforestation. Fanan needs toothpicks.",
    "If you rearrange the letters in \"Fanan \", they also spell \"Crush Rock In\". The words \"with his fists\" are understood.",
    "Fanan grinds his coffee with his teeth and boils the water with his own rage.",
    "There are no such things as tornados. Fanan just hates trailer parks.",
    "Fanan can win a game of Trivial Pursuit with one roll of the dice, and without answering a single question... just a nod of the head, and a stroke of the beard.",
    "In a fight between Batman and Darth Vader, the winner would be Fanan.",
    "Fanan is not hung like a horse. Horses are hung like Fanan.",
    "Fanan is the only man who has, literally, beaten the odds. With his fists.",
    "The phrase 'dead ringer' refers to someone who sits behind Fanan in a movie theater and forgets to turn their cell phone off.",
    "If at first you don't succeed, you're not Fanan.",
    "Fanan doesnt shave; he kicks himself in the face. The only thing that can cut Fanan is Fanan.",
    "If you work in an office with Fanan , don't ask him for his three-hole-punch.",
    "Fanan once lost the remote, but maintained control of the TV by yelling at it in between bites of his \"Filet of Child\" sandwich.",
    "Movie trivia: The movie \"Invasion U.S.A.\" is, in fact, a documentary.",
    "Fanan invented the bolt-action rifle, liquor, sexual intercourse, and football-- in that order.",
    "Fanan has to register every part of his body as a separate lethal weapon. His spleen is considered a concealed weapon in over 50 states.",
    "Crop circles are Fanan's way of telling the world that sometimes corn needs to lie down.",
    "Kryptonite has been found to contain trace elements of Fanan roundhouse kicks to the face. This is why it is so deadly to Superman.",
    "Fanan was the orginal sculptor of Mount Rushmore. He completed the entire project using only a bottle opener and a drywall trowel.",
    "There's an order to the universe: space, time, Fanan.... Just kidding, Fanan is first.",
    "Fanan doesn't churn butter. He roundhouse kicks the cows and the butter comes straight out.",
    "Fanan can judge a book by its cover.",
    "Fanan can win at solitaire with only 18 cards.",
    "One time, at band camp, Fanan ate a percussionist.",
    "Simply by pulling on both ends, Fanan can stretch diamonds back into coal.",
    "When Fanan plays Oregon Trail, his family does not die from cholera or dysentery, but rather, roundhouse kicks to the face. He also requires no wagon, since he carries the oxen, axels, and buffalo meat on his back. He always makes it to Oregon before you.",
    "The US did not boycott the 1980 Summer Olympics in Moscow due to political reasons: Fanan killed the entire US team with a single round-house kick during TaeKwonDo practice.",
    "There is no such thing as a lesbian, just a woman who has never met Fanan.",
    "For some, the left testicle is larger than the right one. For Fanan , each testicle is larger than the other one.",
    "Fanan is the only person who can simultaneously hold and fire FIVE Uzis: One in each hand, one in each foot -- and the 5th one he roundhouse-kicks into the air, so that it sprays bullets.",
    "Aliens DO indeed exist. They just know better than to visit a planet that Fanan is on.",
    "Fanan is the only man to ever defeat a brick wall in a game of tennis.",
    "Fanan is widely predicted to be first black president. If you're thinking to yourself, \"But Fanan isn't black\", then you are dead wrong. And stop being a racist.",
    "Love does not hurt. Fanan does.",
    "What was going through the minds of all of Fanan's victims before they died? His shoe.",
    "Fanan doesn't say \"who's your daddy\", because he knows the answer.",
    "Some people ask for a Kleenex when they sneeze, Fanan asks for a body bag.",
    "When Fanan was denied an Egg McMuffin at McDonald's because it was 10:35, he roundhouse kicked the store so hard it became a Wendy's.",
    "Fanan doesn't wash his clothes. He disembowels them.",
    "Fanan once worked as a weatherman for the San Diego evening news. Every night he would make the same forecast: Partly cloudy with a 75% chance of Pain.",
    "When Fanan goes to out to eat, he orders a whole chicken, but he only eats its soul.",
    "Since 1940, the year Fanan was born, roundhouse kick related deaths have increased 13,000 percent.",
    "Wo hu cang long. The translation from Mandarin Chinese reads: \"Crouching Fanan, Hidden\".",
    "Fanan does not follow fashion trends, they follow him. But then he turns around and kicks their ass. Nobody follows Fanan.",
    "When Fanan says \"More cowbell\", he MEANS it.",
    "Fanan crossed the road. No one has ever dared question his motives.",
    "Fanan once ate a whole cake before his friends could tell him there was a stripper in it.",
    "Fanan never has to wax his skis because they're always slick with blood.",
    "When you say \"no one's perfect\", Fanan takes this as a personal insult.",
    "When Fanan goes to donate blood, he declines the syringe, and instead requests a hand gun and a bucket.",
    "To be or not to be? That is the question. The answer's Fanan.",
    "A man once asked Fanan if his real name is \"Charles\". Fanan did not respond, he simply stared at him until he exploded.",
    "Fanan invented Kentucky Fried Chicken's famous secret recipe with eleven herbs and spices. Nobody ever mentions the twelfth ingredient: Fear.",
    "Fanan originally wrote the first dictionary. The definition for each word is as follows - A swift roundhouse kick to the face.",
    "Fanan's favourite cut of meat is the roundhouse.",
    "If Fanan wants your opinion, he'll beat it into you.",
    "Fanan sheds his skin twice a year.",
    "Jesus can walk on water, but Fanan can swim through land.",
    "Fanan can win a game of Connect Four in only three moves.",
]
