# -*- coding: utf-8 -*-

# Source: https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:Lista_de_erros_comuns/M%C3%A1quinas

grammar = {
    "contruído": "construído",
    "os seu": "os seus",
    "paralização": "paralisação",
    "espectativas": "expectativas",
    "vídeo-clipes": "videoclipes",
    "heterosexuais": "heterossexuais",
    "paraizo": "paraíso",
    "esitaram": "hesitaram",
    "protejida": "protegida",
    "exeto": "excepto",
    "ultra-v": "ultrav",
    "associção": "associação",
    "descubrire": "descobrire",
    "própias": "próprias",
    "confudir": "confundir",
    "séc. I": "século I",
    "séc. X": "século X",
    "séc. V": "século V",
    "bastate": "bastante",
    "chamdo": "chamado",
    "chamda": "chamada",
    "vizualizar": "visualizar",
    "intrumental": "instrumental",
    "acesssados": "acessados",
    "indefenições": "indefinições",
    "previlégios": "privilégios",
    "indefenir": "indefinir",
    "borburinho": "burburinho",
    "repercução": "repercussão",
    "obssessão": "obsessão",
    "estabelecimentes": "estabelecimentos",
    "especialisado": "especializado",
    "haviam poucos": "havia poucos",
    "acreanos": "acrianos",
    "especialisada": "especializada",
    "ernegia": "energia",
    "proceços": "processos",
    "assasinato": "assassinato",
    "descubrimento": "descobrimento",
    "yôga": "ioga",
    "comisão": "comissão",
    "nessecidade": "necessidade",
    "avogrado": "Avogadro",
    "intertido": "entretido",
    "custumavam": "costumavam",
    "estreiado": "estreado",
    "coletânias": "coletâneas",
    "alcólicos": "alcoólicos",
    "previnir": "prevenir",
    "estreiada": "estreada",
    "escerda": "esquerda",
    "haviam vários": "havia vários",
    "das seus": "dos seus",
    "interviste": "intervieste",
    "prosseço": "processo",
    "dos suas": "des suas",
    "progamas": "programas",
    "femeninos": "femininos",
    "coletânia": "coletânea",
    "epecial": "especial",
    "esitou": "hesitou",
    "Bavaria": "Baviera",
    "Autoretrato": "Autorretrato",
    "principalemente": "principalmente",
    "Chopp": "Chope",
    "século 4": "século IV",
    "periudos": "períodos",
    "quizeram": "quiseram",
    "despensável": "dispensável",
    "individado": "endividado",
    "ressucitou": "ressuscitou",
    "individada": "endividada",
    "Acreano": "Acriano",
    "tragetoria": "trajetória",
    "banca-rota": "bancarrota",
    "invéz": "invés",
    "asim": "assim",
    "entitular": "intitular",
    "requesito": "requisito",
    "exdrúxulas": "esdrúxulas",
    "Azaléia": "Azálea",
    "entitulados": "intitulados",
    "despensáveis": "dispensáveis",
    "imuno-deficiências": "imunodeficiências",
    "auto-biografia": "autobiografia",
    "verção": "versão",
    "paralizado": "paralisado",
    "dignatário": "dignitário",
    "errupção": "erupção",
    "dignatária": "dignitária",
    "creação": "criação",
    "contruir": "construir",
    "paralizada": "paralisada",
    "partipação": "participação",
    "reteram": "retiveram",
    "hectar": "hectare",
    "pretenssão": "pretensão",
    "expontâneas": "espontâneas",
    "pertubar": "perturbar",
    "nonagessimo": "nonagésimo",
    "tijela": "tigela",
    "calsado": "calçado",
    "açoreanas": "açorianas",
    "excusas": "escusas",
    "descubriram": "descobriram",
    "crâneo": "crânio",
    "indepedentes": "independentes",
    "discuções": "discussões",
    "contrução": "construção",
    "ethanol": "etanol",
    "u.m.a": "u",
    "número de mols": "quantidade de matéria",
    "preciza": "precisa",
    "séc. XIV": "século XIV",
    "aterisagem": "aterrissagem",
    "femeninismo": "femininismo",
    "dirgido": "dirigido",
    "calvice": "calvície",
    "avulsso": "avulso",
    "igiene": "higiene",
    "miceis": "mísseis",
    "molaridade": "concentração em quantidade de matéria",
    "expontânea": "espontânea",
    "expontâneo": "espontâneo",
    "video game": "videogame",
    "conciderados": "considerados",
    "ao meu ver": "a meu ver",
    "neo-liberais": "neoliberais",
    "azaléia": "azaléa",
    "persoangem": "personagem",
    "propias": "próprias",
    "convidade": "convidado",
    "derrepente": "de repente",
    "sejem": "sejam",
    "quizer": "quiser",
    "Freis": "Frades",
    "século 3": "século III",
    "podessem": "pudessem",
    "periudo": "período",
    "iorgute": "iogurte",
    "quizeres": "quiseres",
    "própio": "próprio",
    "própia": "própria",
    "corrijiam": "corrigiam",
    "aste": "haste",
    "seje": "seja",
    "campioes": "campeões",
    "semi finais": "semifinais",
    "auto-biografias": "autobiografias",
    "grau centígrado": "grau Celsius",
    "difrentes": "diferentes",
    "9º posição": "9ª posição",
    "geneceu": "gineceu",
    "Portugual": "Portugal",
    "entitulado": "intitulado",
    "cujos os": "cujos",
    "ispirar": "inspirar",
    "excusa": "escusa",
    "corçario": "corsário",
    "esquesitas": "esquisitas",
    "companias": "companhias",
    "impresa": "empresa",
    "entitulada": "intitulada",
    "exdrúxula": "esdrúxula",
    "exitaram": "hesitaram",
    "descubre": "descobre",
    "míceis": "mísseis",
    "excavar": "escavar",
    "alcolicos": "alcoólicos",
    "opurtunidade": "oportunidade",
    "expontâneos": "espontâneos",
    "exdrúxulo": "esdrúxulo",
    "vasão": "vazão",
    "hilariedade": "hilaridade",
    "bandeija": "bandeja",
    "lojica": "lógica",
    "nonagessima": "nonagésima",
    "deisponiveis": "disponíveis",
    "espectativa": "expectativa",
    "aviasão": "aviação",
    "etinias": "etnias",
    "conecções": "conexões",
    "concideradas": "consideradas",
    "neo-darwinismo": "neodarwinismo",
    "definitamente": "definitivamente",
    "diverssas": "diversas",
    "catalizada": "catalisada",
    "proceso": "processo",
    "diminue": "diminui",
    "EP's": "EP",
    "quizerem": "quiserem",
    "dignatárias": "dignitárias",
    "espetativas": "expectativas",
    "Ascenção": "Ascensão",
    "suceso": "sucesso",
    "siginifica": "significa",
    "pocuo": "pouco",
    "remanecentes": "remanescentes",
    "traser": "trazer",
    "tils": "tiles",
    "bevocar": "invocar",
    "tranformar": "transformar",
    "tranformação": "transformação",
    "cabelereiro": "cabeleireiro",
    "uzados": "usados",
    "palvras": "palavras",
    "sócio-culturais": "socioculturais",
    "exepção": "excepção",
    "beige": "bege",
    "extenderam": "estenderam",
    "pretencioso": "pretensioso",
    "espulsou": "expulsou",
    "abitual": "habitual",
    "indentidades": "identidades",
    "lisongea": "lisonjeia",
    "bi-campeão": "bicampeão",
    "semi-finais": "semifinais",
    "vídeo-clipe": "videoclipe",
    "intigração": "integração",
    "ritimo": "ritmo",
    "possue": "possui",
    "interviu": "interveio",
    "atravez": "através",
    "do suas": "de suas",
    "geometricas": "geométricos",
    "Irizar": "Irisar",
    "omem": "homem",
    "indiguinar": "indignar",
    "século 20": "século XX",
    "concretisar": "concretizar",
    "suspenção": "suspensão",
    "semi presidencialismos": "semipresidencialismos",
    "seguites": "seguintes",
    "issu": "isso",
    "precizam": "precisam",
    "amargúria": "amargura",
    "atravéz": "através",
    "contribue": "contribui",
    "acessoria": "assessoria",
    "tabém": "também",
    "indefenição": "indefinição",
    "reestabelecida": "restabelecida",
    "sucesos": "sucessos",
    "neo liberais": "neoliberais",
    "caiem": "caem",
    "custuma": "costuma",
    "reestabelecido": "restabelecido",
    "custume": "costume",
    "logista": "lojista",
    "admnistração": "administração",
    "suçeso": "sucesso",
    "condissão": "condição",
    "afim": "a fim",
    "memso": "mesmo",
    "descubrimentos": "descobrimentos",
    "burborinho": "burburinho",
    "número de moles": "quantidade de matéria",
    "corinthiano": "corintiano",
    "ultilizada": "utilizada",
    "Mantia": "Mantinha",
    "corinthiana": "corintiana",
    "ressucitar": "ressuscitar",
    "esquesita": "esquisita",
    "viros": "vírus",
    "prestaçãões": "prestações",
    "Guizo": "Guiso",
    "reestabelecimento": "restabelecimento",
    "largartixa": "lagartixa",
    "esquesito": "esquisito",
    "entitula": "intitula",
    "erói": "herói",
    "juridição": "jurisdição",
    "indepedente": "independente",
    "dijitara": "digitara",
    "desprotejidos": "desprotegidos",
    "exijências": "exigências",
    "nonagéssima": "nonagésima",
    "custumes": "costumes",
    "para-quedas": "paraquedas",
    "defenir": "definir",
    "surgio": "surgiu",
    "nonagéssimo": "nonagésimo",
    "successos": "sucessos",
    "perpectivas": "perspectivas",
    "Semi-presidencialismo": "Semipresidencialismo",
    "cazar": "casar",
    "neo zelandesa": "neozelandesa",
    "respresentação": "representação",
    "Bertold Brecht": "Bertolt Brecht",
    "semi-precioso": "semiprecioso",
    "univercidades": "universidades",
    "derepente": "de repente",
    "obsecado": "obcecado",
    "deichar": "deixar",
    "interviram": "intervieram",
    "logistas": "lojistas",
    "hoxigenio": "oxigênio",
    "contruido": "construído",
    "imprenssa": "imprensa",
    "ultra-violeta": "ultravioleta",
    "sombrancelha": "sobrancelha",
    "contruídos": "construídos",
    "excessao": "exceção",
    "anciosas": "ansiosas",
    "Bahiano": "Baiano",
    "setessentos": "setecentos",
    "ultilizado": "utilizado",
    "Bahiana": "Baiana",
    "homosexuais": "homossexuais",
    "obteu": "obteve",
    "admnistrar": "administrar",
    "fizestes": "fizeste",
    "própios": "próprios",
    "especialisados": "especializados",
    "principlamente": "principalmente",
    "multi-uso": " multiúso",
    "sUSpEITu ": "Suspeito",
    "neo-liberal": "neoliberal",
    "comisões": "comissões",
    "massiça": "maciça",
    "siginificado": "significado",
    "exita": "hesita",
    "massiço": "maciço",
    "arquipelogo": "arquipélago",
    "intrumento": "instrumento",
    "extendendo": "estendendo",
    "naum": "não",
    "repercursão": "repercussão",
    "paraízos": "paraísos",
    "sussesso": "sucesso",
    "ingreja": "igreja",
    "entretando": "entretanto",
    "uzar": "usar",
    "Açoreanos": "Açorianos",
    "tetra-hidrofurano": "tetraidrofurano",
    "indioma": "idioma",
    "em uma": " numa",
    "pseudo-ciência": "pseudociência",
    "depedente": "dependente",
    "ect": "etc",
    "exijência": "exigência",
    "algorítimo": "algoritmo",
    "defeniçao": "definição",
    "campiao": "campeão",
    "prosceços": "processos",
    "argerino": "argelino",
    "ressussitar": "ressuscitar",
    "compreenssão": "compreensão",
    "hambiente": "ambiente",
    "ocoreu": "ocorreu",
    "neo liberal": "neoliberal",
    "protejidas": "protegidas",
    "adiquiriu": "adquiriu",
    "presonagem": "personagem",
    "magestades": "majestades",
    "semi-final": "semifinal",
    "bahianos": "baianos",
    "adiquirir": "adquirir",
    "ecessão": "exceção",
    "propios": "próprios",
    "mangericos": "manjericos",
    "peso molecular": "massa molecular",
    "desembro": "Dezembro",
    "discursão": "discussão",
    "elacção": "elação",
    "previlégio": "privilégio",
    "proprietario": "propietário",
    "Brazil": "Brasil",
    "escerdas": "esquerdas",
    "anti depressivo": "antidepressivo",
    "deiche": "deixe",
    "Guiza": "Guisa",
    "dignatários": "dignitários",
    "acessores": "assessores",
    "vitori@": "vitória",
    "encima d": "em cima d",
    "decer": "descer",
    "concerteza": "com certeza",
    "nacimento": "nascimento",
    "suseços": "sucessos",
    "biograifa": "biografia",
    "saiem": "saem",
    "reestabelecidas": "restabelecidas",
    "sussessos": "sucessos",
    "atráz": "atrás",
    "continar": "continuar",
    "fimeninismos": "femininismos",
    "semi-presidencialista": "semipresidencialista",
    "semi presidencialistas": "semipresidencialistas",
    "ponteagudas": "pontiagudas",
    "catalizador": "catalisador",
    "ultra-p": "ultrap",
    "lisonjea": "lisonjeia",
    "atraz": "atrás",
    "banca-rrota": "bancarrota",
    "mantesse": "mantivesse",
    "estaçãoos": "estações",
    "altoridades": "autoridades",
    "criaças": "crianças",
    "eplepsia": "epilepsia",
    "dsenho": "desenho",
    "rítimo": "ritmo",
    "aver": "haver",
    "arcoiris": "arco-íris",
    "dijita": "digita",
    "analizarem": "analisarem",
    "neo-zelandesa": "neozelandesa",
    "albums": "álbuns",
    "aritimética": "aritmética",
    "igienico": "higiênico",
    "seissentos": "seiscentos",
    "individados": "endividados",
    "uzou": "usou",
    "neo-zelandês": "neozelandês",
    "trez": "três",
    "grau centigrado": "grau Celsius",
    "imuno-deficiência": "imunodeficiência",
    "Abilidades": "Habilidades",
    "Acreana": "Acriana",
    "exelentes": "excelentes",
    "Femenino": "Feminino",
    "despensavel": "dispensável",
    "porisso": "por isso",
    "Brazão": "Brasão",
    "poblema": "problema",
    "permenor": "pormenor",
    "comisoes": "comissões",
    "converçao": "conversão",
    "pesquiza": "pesquisa",
    "reteu": "reteve",
    "analizando": "analisando",
    "Açoreana": "Açoriana",
    "contratato": "contratado",
    "anciosamente": "ansiosamente",
    "quizesse": "quisesse",
    "Açoreano": "Açoriano",
    "menas": "menos",
    "desprotejido": "desprotegido",
    "pertubado": "perturbado",
    "nacido": "nascido",
    "naun ": "não",
    "precurssora": "precursora",
    "grau centígrados": "grau Celsius",
    "suçesos": "sucessos",
    "acesssadas": "acessadas",
    "nacida": "nascida",
    "desprotejida": "desprotegida",
    "sócio-cultural": "sociocultural",
    "discursso": "discurso",
    "cujas as": "cujas",
    "invez": "invés",
    "lisongearam": "lisonjearam",
    "jeropiga": "geropiga",
    "continou": "continuou",
    "infra vermelho": "infravermelho",
    "2º posição": "2ª posição",
    "rítimos": "ritmos",
    "eciclopedia": "enciclopédia",
    "exelente": "excelente",
    "oficilamente": "oficialmente",
    "beiges": "beges",
    "seculo 19": "século XIX",
    "esquesitos": "esquisitos",
    "desprotejidas": "desprotegidas",
    "nenum": "nenhum",
    "grau kelvin": "Kelvin",
    "melhores classificados": "mais bem classificados",
    "pq? ": "por que? ",
    "aerosol": "aerossol",
    "elice": "hélice",
    "gorgetas": "gorjetas",
    "pára-quedas": "paraquedas",
    "Copenhagen": "Copenhague",
    "víros": "vírus",
    "individadas": "endividadas",
    "estutura": "estrutura",
    "beijes": "beges",
    "acessoras": "assessoras",
    "pascais": "pascals",
    "bussula": "bússola",
    "largarto": "lagarto",
    "cidadães": "cidadãos",
    "protejido": "protegido",
    "muinto": "muito",
    "esturquiram": "extorquiram",
    "progama": "programa",
    "fórums": "fóruns",
    "despensaveis": "dispensáveis",
    "oje": "hoje",
    "açoes": "acções",
    "per capta": "per capita",
    "NAUm ": "não",
    "pobrema": "problema",
    "oxido-redução": "oxirredução",
    "tembém": "também",
    "denovo": "de novo",
    "custumava": "costumava",
    "do sua": "de sua",
    "melhores colocados": "mais bem colocados",
    "intensão": "intenção",
    "faser": "fazer",
    "successo": "sucesso",
    "dispender": "despender",
    "geometrica": "geométrico",
    "egipsio": "egípcio",
    "boeiro": "bueiro",
    "compreenções": "compreensões",
    "vez enquando": "vez em quando",
    "desesseis": "dezesseis",
    "reinvindicação": "reivindicação",
    "infra-vermelho": "infravermelho",
    "compreenssões": "compreensões",
    "propiedade": "propriedade",
    "esteje": "esteja",
    "inflacção": "inflação",
    "metereologia": "meteorologia",
    "progamador": "programador",
    "requis": "requereu",
    "estreiou": "estreou",
    "assasinado": "assassinado",
    "giroscopico": "giroscópio",
    "infra vermelhos": "infravermelhos",
    "excessões": "exceções",
    "excavações": "escavações",
    "intervido": "intervindo",
    "cujo o": "cujo",
    "apezar": "apesar",
    "aguns": "alguns",
    "iper": "hiper",
    "manuntenção": "manutenção",
    "munto": "muito",
    "dibre": "drible",
    "pesonagem": "personagem",
    "estorquir": "extorquir",
    "fimeninos": "femininos",
    "invensivel": "invencível",
    "quandos": "quando",
    "entertido": "entretido",
    "alcólico": "alcoólico",
    "em meado": "em meados",
    "Campionato": "Campeonato",
    "pricipais": "principais",
    "converssão": "conversão",
    "fimenino": "feminino",
    "deseçeis": "dezesseis",
    "anti-vírus": "antivírus",
    "dificulidade": "dificuldade",
    "screenshot": "captura de ecrã",
    "quizessem": "quisessem",
    "trasnportes": "transportes",
    "períudos": "períodos",
    "catequisar": "catequizar",
    "milões": "milhões",
    "principamente": "principalmente",
    "corrijir": "corrigir",
    "acesssada": "acessada",
    "enquando": "enquanto",
    "pertubando": "perturbando",
    "femeninismos": "femininismos",
    "prosceço": "processo",
    "azas": "asas",
    "Beneficiente": "Beneficente",
    "reinterar": "reiterar",
    "dijitar": "digitar",
    "crâneos": "crânios",
    "flôrs": "flores",
    "trasnporte": "transporte",
    "pertecentes": "pertencentes",
    "indiomas": "idiomas",
    "algeriano": "argelino",
    "licensa": "licença",
    "percursoras": "precursoras",
    "gorgeta": "gorjeta",
    "ilacção": "ilação",
    "estorquiu": "extorquiu",
    "tranformado": "transformado",
    "coalisão": "coalizão",
    "grangear": "granjear",
    "verçoes": "versões",
    "personalisar": "personalizar",
    "ipopótamo": "hipopótamo",
    "fimeninismo": "femininismo",
    "co-habitação": "coabitação",
    "orta": "horta",
    "cazamento": "casamento",
    "simplemente": "simplesmente",
    "cazaram": "casaram",
    "tri-campeão": "tricampeão",
    "defenição": "definição",
    "biograifas": "biografias",
    "imenente": "iminente",
    "abilidade": "habilidade",
    "nescessária": "necessária",
    "lisongeara": "lisonjeara",
    "o síndrome": "a síndrome",
    "geito": "jeito",
    "conciderada": "considerada",
    "invenssível": "invencível",
    "proscesos": "processos",
    "campionatos": "campeonatos",
    "nescessário": "necessário",
    "adimitiu": "admitiu",
    "verçao": "versão",
    "seguite": "seguinte",
    "adimitir": "admitir",
    "comnosco": "connosco",
    "rectaguarda": "retaguarda",
    "neo zelandês": "neozelandês",
    "compania": "companhia",
    "extendida": "estendida",
    "homosexual": "homossexual",
    "previlegio": "privilégio",
    "armonia": "harmonia",
    "ropa": "roupa",
    "acesssado": "acessado",
    "prescisa": "precisa",
    "ressucitaram": "ressuscitaram",
    "exdrúxulos": "esdrúxulos",
    "esturquiu": "extorquiu",
    "estva": "estava",
    "Xuxu": "Chuchu",
    "penta-campeão": "pentacampeão",
    "esturquir": "extorquir",
    "suseço": "sucesso",
    "extendido": "estendido",
    "ascençao": "ascensão",
    "mícil": "míssil",
    "calvíce": "calvície",
    "criaça": "criança",
    "à muito tempo": "há muito tempo",
    "ferverosos": "fervorosos",
    "beije": "bege",
    "tratrahidrofurano": "tetraidrofurano",
    "protejidos": "protegidos",
    "estorquiram": "extorquiram",
    "acessor": "assessor",
    "espetativa": "expectativa",
    "conecção": "conexão",
    "catequisador": "catequizador",
    "analizar": "analisar",
    "vc": "você",
    "bancarota": "bancarrota",
    "proceço": "processo",
    "massiços": "maciços",
    "algorítimos": "algoritmos",
    "aterissagem": "aterrissagem",
    "vizualiza": "visualiza",
    "campião": "campeão",
    "percurssão": "percussão",
    "anti aéreo": "antiaéreo",
    "semi-círculos": "semicírculos",
    "relidade": "realidade",
    "acreanas": "acrianas",
    "dijitaram": "digitaram",
    "estinto": "extinto",
    "prosceso": "processo",
    "uqe": "que",
    "peso atômico": "massa atômica",
    "excusado": "escusado",
    "veses": "vezes",
    "personalisação": "personalização",
    "exitem": "existem",
    "pricipal": "principal",
    "defenições": "definições",
    "eciclopédia": "enciclopédia",
    "indiguinado": "indignado",
    "têmporo-mandibular": "temporomandibular",
    "extendidas": "estendidas",
    "corrijiram": "corrigiram",
    "perpectiva": "perspectiva",
    "obteram": "obtiveram",
    "extendeu": "estendeu",
    "ressucitado": "ressuscitado",
    "lêm": "lêem",
    "extender": "estender",
    "kilômetro": "quilômetro",
    "expectador": "espectador",
    "vizualização": "visualização",
    "yoga": "ioga",
    "de encontro ao": "ao encontro do",
    "mecheram": "mexeram",
    "indiguinação": "indignação",
    "manteram": "mantiveram",
    "Wikimapa": "WikiMapia",
    "Guizar": "Guisar",
    "Meche": "Mexe",
    "ecessões": "exceções",
    "algus": "alguns",
    "verções": "versões",
    "exite": "existe",
    "arcoíris": "arco-íris",
    "diverssos": "diversos",
    "hoxigênio": "oxigênio",
    "semi-presidencialistas": "semipresidencialistas",
    "xafariz": "chafariz",
    "personagen": "personagem",
    "gipe": "jipe",
    "excessão": "exceção",
    "mangerico": "manjerico",
    "personalisou": "personalizou",
    "as sua": "as suas",
    "kilo": "quilograma",
    "descubrir": "descobrir",
    "anciosos": "ansiosos",
    "reestabelecer": "restabelecer",
    "reestabeleceu": "restabeleceu",
    "micil": "míssil",
    "deceram": "desceram",
    "extende": "estende",
    "século 21": "século XXI",
    "Gaz": "Gás",
    "nescessárias": "necessárias",
    "Intenacional": "Internacional",
    "viajens": "viagens",
    "gipes": "jipes",
    "especialisadas": "especializadas",
    "semi preciosos": "semipreciosos",
    "irisar": "irizar",
    "proseço": "processo",
    "a muito tempo": "há muito tempo",
    "entreteram": "entretiveram",
    "tranformou": "transformou",
    "Assasinos": "Assassinos",
    "proseços": "processos",
    "neo-liberalismo": "neoliberalismo",
    "auto-biográfica": "autobiográfica",
    "século 13": "século XIII",
    "deisponivel": "disponível",
    "auto-biográfico": "autobiográfico",
    "século 12": "século XII",
    "Guizado": "Guisado",
    "lisongearou": "lisonjearou",
    "excavação": "escavação",
    "semi-presidencialismos": "semipresidencialismos",
    "celebro": "cérebro",
    "treslagoense": "três-lagoense",
    "dispenderam": "despenderam",
    "houveram": "houve",
    "a a": "a",
    "muintos": "muitos",
    "atris": "actriz",
    "semi final": "semifinal",
    "estintos": "extintos",
    "nescessario": "necessário",
    "cuja a": "cuja",
    "corinthianos": "corintianos",
    "da seu": "do seu",
    "estabelecimente": "estabelecimento",
    "hambientes": "ambientes",
    "reibi": "râguebi",
    "estreiaram": "estrearam",
    "conciderado": "considerado",
    "ressucita": "ressuscita",
    "alcolico": "alcoólico",
    "um um": "um",
    "alcolémia": "alcoolemia",
    "cazara": "casara",
    "qeu": "que",
    "seculo 20": "século XX",
    "seculo 21": "século XXI",
    "forão": "foram",
    "algoritimo": "algoritmo",
    "palvra": "palavra",
    "paraizos": "paraísos",
    "actris": "atriz",
    "podesse": "pudesse",
    "semi círculos": "semicírculos",
    "analiza": "analisa",
    "subjulgar": "subjugar",
    "siguinifica": "significa",
    "comcerteza": "com certeza",
    "pertecente": "pertencente",
    "número de Avogadro": "constante de Avogadro",
    "ciclano": "sicrano",
    "século 8": "século VIII",
    "século 5": "século V",
    "analizado": "analisado",
    "intervi": "intervim",
    "século 6": "século VI",
    "século 1": "século I",
    "tragetória": "trajetória",
    "século 2": "século II",
    "re-escrever": "reescrever",
    "infra-vermelhos": "infravermelhos",
    "1º posição": "1ª posição",
    "infelismente": "infelizmente",
    "adimitiram": "admitiram",
    "Frankstein": "Frankenstein",
    "intervisse": "interviesse",
    "mau estar": "mal-estar",
    "cazou": "casou",
    "paralizar": "paralisar",
    "indentidade": "identidade",
    "depedentes": "dependentes",
    "defenido": "definido",
    "paraízo": "paraíso",
    "repercurssão": "repercussão",
    "haviam muitos": "havia muitos",
    "entreteu": "entreteve",
    "comporam": "compuseram",
    "adimite": "admite",
    "5º posição": "5ª posição",
    "contruída": "construída",
    "século 7": "século VII",
    "períudo": "período",
    "imenência": "iminência",
    "procesos": "processos",
    "tranformações": "transformações",
    "cidadões": "cidadãos",
    "cadaço": "cadarço",
    "uzadas": "usadas",
    "semi precioso": "semiprecioso",
    "síntaze": "síntaxe",
    "vezis": "vezes",
    "viuv@": "viúva",
    "acessora": "assessora",
    "ultra-b": "ultrab",
    "ultra-c": "ultrac",
    "consite": "consiste",
    "ultra-f": "ultraf",
    "heterosexual": "heterossexual",
    "ultra-d": "ultrad",
    "cansão": "canção",
    "invensível": "invencível",
    "ultra-n": "ultran",
    "ultra-l": "ultral",
    "ultra-m": "ultram",
    "neo liberalismo": "neoliberalismo",
    "4º posição": "4ª posição",
    "inclue": "inclui",
    "entreterimento": "entretenimento",
    "irupção": "irrupção",
    "viajem": "viagem",
    "prespectiva": "perspectiva",
    "requesitos": "requisitos",
    "reinvidicação": "reivindicação",
    "mecheu": "mexeu",
    "mecher": "mexer",
    "assasino": "assassino",
    "conclue": "conclui",
    "exitou": "hesitou",
    "univercidade": "universidade",
    "aterrizagem": "aterrissagem",
    "pertuba": "perturba",
    "ancioso": "ansioso",
    "juz": "jus",
    "campiões": "campeões",
    "semi-preciosos": "semipreciosos",
    "analizem": "analisem",
    "posivel": "possível",
    "lójica": "lógica",
    "reinvidicar": "reivindicar",
    "assasinatos": "assassinatos",
    "para mim fazer": "para eu fazer",
    "percursora": "precursora",
    "condissao": "condição",
    "cohabitação": "coabitação",
    "propiedades": "propriedades",
    "semi círculo": "semicírculo",
    "uzado": "usado",
    "neo darwinismo": "neodarwinismo",
    "permenores": "pormenores",
    "furá": "furar",
    "anciosa": "ansiosa",
    "benvindo": "bem-vindo",
    "uzada": "usada",
    "compreenção": "compreensão",
    "muntos": "muitos",
    "propio": "próprio",
    "pedigri": "pedigree",
    "siclano": "sicrano",
    "ressussitado": "ressuscitado",
    "3º posição": "3ª posição",
    "obseção": "obsessão",
    "propia": "própria",
    "Magestade": "Majestade",
    "lisongear": "lisonjear",
    "massiças": "maciças",
    "Bavária": "Baviera",
    "previlegios": "privilégios",
    "iguasu": "Iguaçu",
    "século 15": "século XV",
    "século 14": "século XIV",
    "século 17": "século XVII",
    "século 16": "século XVI",
    "século 11": "século XI",
    "século 10": "século X",
    "ispirou": "inspirou",
    "gáz": "gás",
    "naceu": "nasceu",
    "século 19": "século XIX",
    "século 18": "século XVIII",
    "aterrisagem": "aterrissagem",
    "mais também": "mas também",
    "trasnporta": "transporta",
    "ultilizar": "utilizar",
    "despois": "depois",
    "albun": "álbum",
    "paraliza": "paralisa",
    "videoclip": "videoclipe",
    "intervemos": "intervimos",
    "susseços": "sucessos",
    "altoridade": "autoridade",
    "semi-círculo": "semicírculo",
    "hexa-campeão": "hexacampeão",
    "estreiar": "estrear",
    "exitar": "hesitar",
    "susseço": "sucesso",
    "homosexualidade": "homossexualidade",
    "prosseços": "processos",
    "extende-se": "estende-se",
    "poderam": "puderam",
    "século 9": "século IX",
    "dijitou": "digitou",
    "um síndrome": "uma síndrome",
    "pretenção": "pretensão",
    "manteu": "manteve",
    "converção": "conversão",
    "amandar": "mandar",
    "fizes-te": "fizeste",
    "vies-te": "vieste",
    "viesse-mos": "viessemos",
    "tinha-mos": "tínhamos",
    "tínha-mos": "tínhamos",
    "tive-mos": "tivemos",
    "tivé-mos": "tivemos",
    "quises-te": "quiseste",
    "fosse-mos": "fôssemos",
    "fôsse-mos": "fôssemos",
    "pudes-te": "pudeste",
    "comes-te": "comeste",
    "bebes-te": "bebeste",
    "disses-te": "disseste"
}
